//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDGameEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WDGameEngine.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t attack. You don&apos;t own the country from which you want to attack..
        /// </summary>
        internal static string ATTACK_DONT_OWN_COUNTRY {
            get {
                return ResourceManager.GetString("ATTACK_DONT_OWN_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t attack. You can only attack a country from a neighbouring Country..
        /// </summary>
        internal static string ATTACK_ONLY_NEIGHBOUR {
            get {
                return ResourceManager.GetString("ATTACK_ONLY_NEIGHBOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t attack. You can&apos;t attack a country you allready own..
        /// </summary>
        internal static string ATTACK_OWN_COUNTRY {
            get {
                return ResourceManager.GetString("ATTACK_OWN_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t attack. When you attack with more then three countries you must leave three armies on your country or else atleast one or two depending on how much used in the attack..
        /// </summary>
        internal static string ATTACK_WITH_TO_MANY_ARMIES {
            get {
                return ResourceManager.GetString("ATTACK_WITH_TO_MANY_ARMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add a player because there are no more colors left in playerColorrs.
        /// </summary>
        internal static string CANT_ADD_MORE_PLAYERS_AS_COLORS {
            get {
                return ResourceManager.GetString("CANT_ADD_MORE_PLAYERS_AS_COLORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add a player after the game is started..
        /// </summary>
        internal static string CANT_ADDPLAYER_IF_GAME_STARTED {
            get {
                return ResourceManager.GetString("CANT_ADDPLAYER_IF_GAME_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call Attack. The game is not started..
        /// </summary>
        internal static string CANT_ATTACK_GAME_NOT_STARTED {
            get {
                return ResourceManager.GetString("CANT_ATTACK_GAME_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call Attack. The game is not in the Attack fase..
        /// </summary>
        internal static string CANT_ATTACK_NOT_IN_FASE {
            get {
                return ResourceManager.GetString("CANT_ATTACK_NOT_IN_FASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call ChooseTurnType . The game is not started..
        /// </summary>
        internal static string CANT_CHOOSETURNTYPE_GAME_NOT_STARTED {
            get {
                return ResourceManager.GetString("CANT_CHOOSETURNTYPE_GAME_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call ChooseTurnType . The game is not in the ChooseTurnType fase..
        /// </summary>
        internal static string CANT_CHOOSETURNTYPE_NOT_IN_FASE {
            get {
                return ResourceManager.GetString("CANT_CHOOSETURNTYPE_NOT_IN_FASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call ExchangeCards. The game is not started. .
        /// </summary>
        internal static string CANT_EXCHANGECARDS_GAME_NOT_STARTED {
            get {
                return ResourceManager.GetString("CANT_EXCHANGECARDS_GAME_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call ExchangeCards. The game is not in the ExchangeCards fase..
        /// </summary>
        internal static string CANT_EXCHANGECARDS_NOT_IN_FASE {
            get {
                return ResourceManager.GetString("CANT_EXCHANGECARDS_NOT_IN_FASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call GoToNextFase. The game is ended..
        /// </summary>
        internal static string CANT_GOTONEXTFASE_GAME_IS_ENDED {
            get {
                return ResourceManager.GetString("CANT_GOTONEXTFASE_GAME_IS_ENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call GoToNextFase. The game is not started..
        /// </summary>
        internal static string CANT_GOTONEXTFASE_GAME_NOT_STARTED {
            get {
                return ResourceManager.GetString("CANT_GOTONEXTFASE_GAME_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t MoveArmies. You can&apos;t move more or all armies on the a Country to the other Country. You must leace at least one armie on the the Country..
        /// </summary>
        internal static string CANT_MOVE_ALL_OR_MORE_ARMIES {
            get {
                return ResourceManager.GetString("CANT_MOVE_ALL_OR_MORE_ARMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t MoveArmies. You can only move armies from or to a Country you just attacked..
        /// </summary>
        internal static string CANT_MOVE_FROM_OTHER_COUNTRIES {
            get {
                return ResourceManager.GetString("CANT_MOVE_FROM_OTHER_COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call MoveArmies. The game is not started..
        /// </summary>
        internal static string CANT_MOVEARMIES_GAME_NOT_STARTED {
            get {
                return ResourceManager.GetString("CANT_MOVEARMIES_GAME_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call MoveArmies. The game is not in the MoveArmiesAfterAttack or MoveArmiesEndOfTurn fase..
        /// </summary>
        internal static string CANT_MOVEARMIES_NOT_IN_FASE {
            get {
                return ResourceManager.GetString("CANT_MOVEARMIES_NOT_IN_FASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t PlaceNewArmies. You can&apos;t place more armies as you own..
        /// </summary>
        internal static string CANT_PLACE_MORE_AS_OWNED {
            get {
                return ResourceManager.GetString("CANT_PLACE_MORE_AS_OWNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call PlaceNewArmies. The game is not started..
        /// </summary>
        internal static string CANT_PLACENEWARMIES_GAME_NOT_STARTED {
            get {
                return ResourceManager.GetString("CANT_PLACENEWARMIES_GAME_NOT_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call PlaceNewArmies. The game is not in the PlaceNewArmies or PlaceInitialArmies fase..
        /// </summary>
        internal static string CANT_PLACENEWARMIES_NOT_IN_FASE {
            get {
                return ResourceManager.GetString("CANT_PLACENEWARMIES_NOT_IN_FASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start the game. There are less players added as defined in MinimumNumberPlayers in the config..
        /// </summary>
        internal static string CANT_START_WITH_LESS_MIN_PLAYERS {
            get {
                return ResourceManager.GetString("CANT_START_WITH_LESS_MIN_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t MoveArmies. The to and from country can&apos;t be the same..
        /// </summary>
        internal static string FROM_AND_TO_CANT_BE_THE_SAME {
            get {
                return ResourceManager.GetString("FROM_AND_TO_CANT_BE_THE_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t start the game.The game is already started..
        /// </summary>
        internal static string GAME_ALREADY_STARTED {
            get {
                return ResourceManager.GetString("GAME_ALREADY_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t GoToNextFase. You hold to many cards. Exchanges cards before calling GoToNextFase..
        /// </summary>
        internal static string HOLD_TO_MANY_CARDS {
            get {
                return ResourceManager.GetString("HOLD_TO_MANY_CARDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t MoveArmies. You can only move to a country from a neighbouring country..
        /// </summary>
        internal static string MOVE_ONLY_NEIGHBOUR {
            get {
                return ResourceManager.GetString("MOVE_ONLY_NEIGHBOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t call MoveArmies. You can only move armies once in a fase. Call GoToNextFase..
        /// </summary>
        internal static string MOVE_ONLY_ONCE_IN_A_TURN {
            get {
                return ResourceManager.GetString("MOVE_ONLY_ONCE_IN_A_TURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t MoveArmies. You must own the to and from country..
        /// </summary>
        internal static string MOVEARMIES_DONT_OWN_COUNTRY {
            get {
                return ResourceManager.GetString("MOVEARMIES_DONT_OWN_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t attack. You must at least attack with one armie..
        /// </summary>
        internal static string MUST_ATTACK_AT_LEAST_ONE_ARMIE {
            get {
                return ResourceManager.GetString("MUST_ATTACK_AT_LEAST_ONE_ARMIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t GoToNextFase. You must choose a TurnType before calling GoToNextFase..
        /// </summary>
        internal static string MUST_CHOOSETURNTYPE {
            get {
                return ResourceManager.GetString("MUST_CHOOSETURNTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t MoveArmies. You must at least leave the amount of armies used in the last attack on the country you just won..
        /// </summary>
        internal static string MUST_LEAVE_ATTACKING_COUNTRIES {
            get {
                return ResourceManager.GetString("MUST_LEAVE_ATTACKING_COUNTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t MoveArmies. You must at least move one country..
        /// </summary>
        internal static string MUST_MOVE_AT_LEAST_ONE_ARMIE {
            get {
                return ResourceManager.GetString("MUST_MOVE_AT_LEAST_ONE_ARMIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t PlaceNewArmies. You must at least place one country..
        /// </summary>
        internal static string MUST_PLACE_AT_LEAST_ONE_ARMIE {
            get {
                return ResourceManager.GetString("MUST_PLACE_AT_LEAST_ONE_ARMIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t PlaceNewArmies. You did not provide a valid country Name..
        /// </summary>
        internal static string NOT_A_VALID_COUNTRY_NAME {
            get {
                return ResourceManager.GetString("NOT_A_VALID_COUNTRY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When calling LoadContinentsAndCountries there where no or not enough countries and/ord continents loaded..
        /// </summary>
        internal static string NOT_LOADED_WORLD_CORRECT {
            get {
                return ResourceManager.GetString("NOT_LOADED_WORLD_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t GoToNextFase. You must place all new armies before calling GoToNextFase..
        /// </summary>
        internal static string PLACE_ALL_NEW_ARMIES {
            get {
                return ResourceManager.GetString("PLACE_ALL_NEW_ARMIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t PlaceNewArmies. You don&apos;t own this country..
        /// </summary>
        internal static string PLACENEWARMIES_DONT_OWN_COUNTRY {
            get {
                return ResourceManager.GetString("PLACENEWARMIES_DONT_OWN_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of playerColors can&apos;t be smaller as the MinimumNumberPlayers defined in the config..
        /// </summary>
        internal static string PLAYER_COLORS_COUNT_SMALLER_MIN_PLAYERS {
            get {
                return ResourceManager.GetString("PLAYER_COLORS_COUNT_SMALLER_MIN_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t GoToNextFase. Something is wrong TurnType should be a valid values but is not..
        /// </summary>
        internal static string WRONG_TURNTYPE {
            get {
                return ResourceManager.GetString("WRONG_TURNTYPE", resourceCulture);
            }
        }
    }
}
